This notebook is used for visualizing the weights of the linear regression model. The weights is from 887 (features) to 3 (output classes).

In [1]:
import numpy as np

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
import sys
sys.path.insert(0, '../')

from linear_regression import LinearRegression

In [4]:
# utility
from utils.config_utils import load_config
from utils.fs_utils import create_folder
from utils.Timer import Timer
from utils import torch_utils

In [5]:
PATH_pretrained = "../models/session_2019-07-21[16_55_19]/model_1.pth"

In [6]:
# define the model
params = load_config("../config.yaml")
model = LinearRegression(params["record_dim"], params["output_dim"])
model.load_state_dict(torch.load(PATH_pretrained))

../utils/config_utils.py:7: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params = yaml.load(f)


IncompatibleKeys(missing_keys=[], unexpected_keys=[])

In [7]:
model.linear.weight

Parameter containing:
tensor([[ 0.0373,  0.0052,  0.0160,  ...,  0.0512, -0.2720,  0.1025],
        [ 0.0257, -0.0052,  0.0587,  ...,  0.0044,  0.1540, -0.0350],
        [-0.0235, -0.0148, -0.0827,  ...,  0.0076,  0.2825, -0.0050]],
       requires_grad=True)

In [8]:
# transder it into the numpy array and do without any gradient
with torch.no_grad():
    lr_weights = model.linear.weight.detach().numpy()

In [9]:
lr_weights

array([[ 0.03733412,  0.00519957,  0.0160424 , ...,  0.05119704,
        -0.2719901 ,  0.10249215],
       [ 0.02568194, -0.00515691,  0.0587229 , ...,  0.0044036 ,
         0.15399663, -0.03498825],
       [-0.02353989, -0.01478315, -0.08269181, ...,  0.00759515,
         0.28253102, -0.00495785]], dtype=float32)

I don't know how to make it clear, so let's get the weights based on each label and the order of the features we concatenated to construct the feature vector.

In [10]:
lr_weights[0, :]

array([ 3.73341218e-02,  5.19956555e-03,  1.60424002e-02, -4.40934598e-02,
        1.93758830e-01, -4.85429436e-01,  1.44762211e-02,  3.35135043e-01,
       -2.10538000e-01, -4.56487745e-01,  1.97834864e-01, -4.81021643e-01,
        4.81391251e-02, -8.09478923e-04, -2.84359176e-02,  5.22283316e-02,
        4.28679064e-02,  2.54911520e-02,  2.93516479e-02, -2.90604591e-01,
       -3.22833002e-01, -2.02790387e-02,  4.93313931e-02, -5.66410720e-02,
        5.18866181e-02, -4.52822819e-02, -1.27534419e-01, -1.73619818e-02,
       -3.80651727e-02, -3.42600763e-01, -2.16048211e-01, -1.85344145e-01,
       -9.54086557e-02,  1.78788841e-01, -8.15628991e-02,  8.91471505e-02,
        1.73166022e-02, -3.90455365e-01, -1.29450202e-01, -2.18504950e-01,
       -8.17657039e-02, -2.48106509e-01,  9.16717872e-02, -4.17604409e-02,
       -5.47241010e-02, -2.34134361e-01, -7.22328275e-02,  3.04115742e-01,
       -1.66310266e-01, -1.16858184e-01, -1.83165759e-01, -1.60087645e-02,
        9.91353393e-02, -

In [13]:
# read in the entire column names and categorical column names
import pickle

folder_name = "./column_names_values/"
entire_column_filename = folder_name + "entire_column_names.pkl"
categorical_column_filename = folder_name + "categorical_column_names.pkl"
categorical_values_filename = folder_name + "categorical_values.pkl"

with open(entire_column_filename, 'rb') as fin:
    entire_column_names = pickle.load(fin)
with open(categorical_column_filename, 'rb') as fin:
    categorical_column_names = pickle.load(fin)
with open(categorical_values_filename, 'rb') as fin:
    categorical_values = pickle.load(fin)

In [17]:
categorical_values

{'SEX': array([1, 2]),
 'HISPANIC': array([0, 1, 9]),
 'HISPOR': array([ 1,  2,  3,  4,  5,  6, 50, 88, 99]),
 'PRIMLANG': array([1, 2, 3, 4, 5, 6, 8, 9]),
 'INSEX': array([-4,  1,  2]),
 'NACCNINR': array([-4,  1,  2,  3,  4,  5,  6, 99]),
 'INRACE': array([-4,  1,  2,  3,  4,  5, 50, 99]),
 'INRELTO': array([-4,  1,  2,  3,  4,  5,  6,  7]),
 'NACCFAM': array([-4,  0,  1,  9]),
 'ANYMEDS': array([-4,  0,  1]),
 'TOBAC30': array([-4,  0,  1,  9]),
 'TOBAC100': array([-4,  0,  1,  9]),
 'PACKSPER': array([-4,  0,  1,  2,  3,  4,  5,  8,  9]),
 'ALCOCCAS': array([-4,  0,  1,  9]),
 'ALCFREQ': array([-4,  0,  1,  2,  3,  4,  8,  9]),
 'CVHATT': array([-4,  0,  1,  2,  9]),
 'HATTMULT': array([-4,  0,  1,  8,  9]),
 'CVAFIB': array([-4,  0,  1,  2,  9]),
 'CVANGIO': array([-4,  0,  1,  2,  9]),
 'CVBYPASS': array([-4,  0,  1,  2,  9]),
 'CVPACDEF': array([-4,  0]),
 'CVPACE': array([-4,  0,  1,  2,  9]),
 'CVCHF': array([-4,  0,  1,  2,  9]),
 'CVANGINA': array([-4,  0,  1,  2,  9]),
 'CV

In [18]:
# get the whole feature names for each entry
whole_feature_names_list= []  # store names for each entry
for col in entire_column_names:
    if col in categorical_column_names:
        # if this is a categorical name
        for value in list(categorical_values[col]):
            whole_feature_names_list.append(col+str(value))
    else:
        whole_feature_names_list.append(col)

In [19]:
len(whole_feature_names_list)

887

In [20]:
whole_feature_names_list

['SEX1',
 'SEX2',
 'HISPANIC0',
 'HISPANIC1',
 'HISPANIC9',
 'HISPOR1',
 'HISPOR2',
 'HISPOR3',
 'HISPOR4',
 'HISPOR5',
 'HISPOR6',
 'HISPOR50',
 'HISPOR88',
 'HISPOR99',
 'PRIMLANG1',
 'PRIMLANG2',
 'PRIMLANG3',
 'PRIMLANG4',
 'PRIMLANG5',
 'PRIMLANG6',
 'PRIMLANG8',
 'PRIMLANG9',
 'EDUC',
 'INSEX-4',
 'INSEX1',
 'INSEX2',
 'NACCNINR-4',
 'NACCNINR1',
 'NACCNINR2',
 'NACCNINR3',
 'NACCNINR4',
 'NACCNINR5',
 'NACCNINR6',
 'NACCNINR99',
 'INRACE-4',
 'INRACE1',
 'INRACE2',
 'INRACE3',
 'INRACE4',
 'INRACE5',
 'INRACE50',
 'INRACE99',
 'INEDUC',
 'INRELTO-4',
 'INRELTO1',
 'INRELTO2',
 'INRELTO3',
 'INRELTO4',
 'INRELTO5',
 'INRELTO6',
 'INRELTO7',
 'NACCFAM-4',
 'NACCFAM0',
 'NACCFAM1',
 'NACCFAM9',
 'ANYMEDS-4',
 'ANYMEDS0',
 'ANYMEDS1',
 'TOBAC30-4',
 'TOBAC300',
 'TOBAC301',
 'TOBAC309',
 'TOBAC100-4',
 'TOBAC1000',
 'TOBAC1001',
 'TOBAC1009',
 'SMOKYRS',
 'PACKSPER-4',
 'PACKSPER0',
 'PACKSPER1',
 'PACKSPER2',
 'PACKSPER3',
 'PACKSPER4',
 'PACKSPER5',
 'PACKSPER8',
 'PACKSPER9',
 'Q

In [21]:
lr_weights.shape

(3, 887)

In [22]:
wll_arr = np.array([[4,5,8],[7,2,0]])
np.argsort(wll_arr, axis=1)

array([[0, 1, 2],
       [2, 1, 0]])

In [23]:
# sort the linear regression weights for each label to see which feature is more important for each label
# NOTE that the order is ascending, so if we want to get the most important ones, we need to reverse it
sort_perm_index = np.argsort(lr_weights, axis=1)

In [24]:
#sort_perm_index[0]
mci_index_descending = sort_perm_index[0][::-1]
alz_index_descending = sort_perm_index[1][::-1]
norm_index_descending = sort_perm_index[2][::-1]

In [25]:
# transfer the name list into a numpy array and resort it according to the sort_perm_index
whole_feature_names_array = np.array(whole_feature_names_list)
# for label 0 (MCI)
mci_feature_names_importance = whole_feature_names_array[mci_index_descending]
# for label 1 (ALZ)
alz_feature_names_importance = whole_feature_names_array[alz_index_descending]
# for label 2 (NORM)
norm_feature_names_importance = whole_feature_names_array[norm_index_descending]

In [26]:
mci_feature_names_importance

array(['PDOTHR1', 'NACCPDMD1', 'NPGRSNH3', 'NACCAPSY1', 'PD1', 'NPGRSNH2',
       'CBSTROKE2', 'HISPOR3', 'INRELTO4', 'RBD1', 'NPLINF1', 'CBSTROKE1',
       'MEMUNITS', 'PSYCDIS9', 'NACCAANX1', 'PTSD2', 'NITESEV3',
       'NPOLD23.0', 'APASEV3', 'PD9', 'NPOLDD30.0', 'CSFABMD1.0',
       'NPHEMO21.0', 'NACCNIHR2', 'TRAUMCHR1', 'NPOLDD20.0', 'NPGRLCH3',
       'HISPOR6', 'ABUSOTHR9', 'HISPANIC9', 'NPOLDD8', 'SEIZURES1',
       'DISNSEV2', 'NACCAAAS1', 'MOTSEV2', 'NACCNSD0', 'NPTDPC0',
       'NACCNINR99', 'NPOLDD12.0', 'CVCHF2', 'NPGRCCA3', 'CBTIA1',
       'ALCOCCAS1', 'MINTTOTS', 'NPWBRWT', 'NPGRHA0', 'DISN1', 'PDOTHR9',
       'NPTDPAN1', 'SCHIZ0', 'APA1', 'CRAFTDTI', 'NACCFAM9', 'TRAILALI',
       'HALLSEV3', 'NACCGDS', 'NPOLDD1', 'NPOLDD21.0', 'TOBAC309',
       'ARTHUNK0', 'CVCHF9', 'DEPOTHR9', 'CVHVALVE0', 'PACKSPER4', 'ANX1',
       'LOGIMEM', 'ARTHTYPE1', 'HALLSEV2', 'TIAMULT8', 'NITE1',
       'UDSVERFN', 'CVPACDEF0', 'TRAILBLI', 'STROKMUL8', 'NACCFORM1',
       'NPOLD30.0', 'C

In [27]:
alz_feature_names_importance

array(['NPGRLCH2', 'NPGRSNH1', 'NPGRHA3', 'EVENTS3', 'NPBNKF1',
       'NPGRLCH9', 'NACCAVAS8', 'NPTDPC1', 'SHOPPING1', 'NPGRCCA2',
       'MEALPREP2', 'NACCBNKF0', 'HYPERTEN2', 'CVHATT1', 'NPOLD32.0',
       'PSYCDIS2', 'NPOLDD43.0', 'GAMES1', 'DIABETES2', 'SHOPPING9',
       'NPHEM1', 'HALL9', 'PRIMLANG6', 'NPTAN7', 'INRACE50', 'TAXES9',
       'MOTSEV3', 'NPOLD33.0', 'HISPOR4', 'NPFIX2', 'TAXES8', 'TRAVEL9',
       'NPOLD12.0', 'NPGRSNH8', 'CSFPTAU', 'NACCNIHR99', 'NPOLD43.0',
       'TRAVEL1', 'PACKSPER2', 'CVOTHR2', 'TAXES2', 'REMDATES2',
       'NPHIST1', 'PDOTHR0', 'NACCNINR4', 'NACCDIED1', 'NPBNKB0',
       'CRAFTCUE1', 'CVCHF1', 'PAYATTN9', 'NPTDPD1', 'BILLS9', 'HISPOR50',
       'GAMES8', 'REMDATES3', 'NPTDPAN2', 'NPGRHA8', 'STOVE9',
       'ARTHSPIN1', 'NPLAC1', 'STOVE3', 'UDSBENRS0', 'CVPACE1',
       'ALCOCCAS0', 'NPWBRF8', 'TRAUMBRF9', 'TRAUMBRF2', 'NCOTHR2',
       'INRELTO3', 'NACCAVAS0', 'NPOLDD32.0', 'ABUSOTHR2', 'DELSEV3',
       'B12DEF1', 'NPTDPD9', 'NPGRLA0', 'BIL

In [28]:
norm_feature_names_importance

array(['HISPOR1', 'NACCNIHR3', 'PACKSPER9', 'NITE9', 'NPOLD31.0',
       'PRIMLANG8', 'UDSBENTD', 'HISPOR5', 'PAYATTN2', 'BOSTON',
       'NPGRHA2', 'NACCEPMD1', 'HISPANIC1', 'TRAVEL8', 'THYROID2',
       'NCOTHR1', 'ANIMALS', 'CRAFTCUE0', 'NPLINF2', 'NACCVASD1',
       'APNEA9', 'TOBAC301', 'MEMUNITS', 'ANXSEV2', 'BILLS8', 'B12DEF9',
       'ANYMEDS0', 'INRELTO2', 'PTSD1', 'VEG', 'CVBYPASS2', 'REMDATES8',
       'NPGRCCA1', 'NACCEMD1', 'INRACE3', 'PACKSPER5', 'NACCNINR3',
       'CSFTTMD1.0', 'CVOTHR9', 'PSYCDIS1', 'PAYATTN8', 'HYPERTEN9',
       'DISNSEV3', 'NACCTBI9', 'EVENTS8', 'HYPERCHO9', 'NPASAN2', 'WAIS',
       'REMDATES0', 'ARTHTYPE2', 'UDSBENRS1', 'CVANGINA1', 'CSFPTMD1.0',
       'NPHEMO11.0', 'INRELTO-4', 'NPOLD40.0', 'CVAFIB1', 'INRELTO7',
       'NPOLDD1', 'INSEX-4', 'NPHIST1', 'TIAMULT0', 'HISPOR50',
       'INRELTO5', 'NACCNINR5', 'NPABAN1', 'NPTDPAN8', 'NACCCSFP0',
       'TBIWOLOS2', 'PSYCDIS2', 'CVOTHR1', 'NPTDPC8', 'NPMICRO2',
       'TBIWOLOS1', 'NACCNSD1', 'TAXES

In [29]:
# to see the top 10 factors which is most important for each 
print("for MCI:", mci_feature_names_importance[:10], "\n")
print("for ALZ:", alz_feature_names_importance[:10], "\n")
print("for NORM:", norm_feature_names_importance[:10], "\n")

for MCI: ['PDOTHR1' 'NACCPDMD1' 'NPGRSNH3' 'NACCAPSY1' 'PD1' 'NPGRSNH2' 'CBSTROKE2'
 'HISPOR3' 'INRELTO4' 'RBD1'] 

for ALZ: ['NPGRLCH2' 'NPGRSNH1' 'NPGRHA3' 'EVENTS3' 'NPBNKF1' 'NPGRLCH9'
 'NACCAVAS8' 'NPTDPC1' 'SHOPPING1' 'NPGRCCA2'] 

for NORM: ['HISPOR1' 'NACCNIHR3' 'PACKSPER9' 'NITE9' 'NPOLD31.0' 'PRIMLANG8'
 'UDSBENTD' 'HISPOR5' 'PAYATTN2' 'BOSTON'] 



In [30]:
categorical_values["TRAUMBRF"]

array([-4,  0,  1,  2,  9])